name: Deploy Staging → Produção

on:
  push:
    branches:
      - staging

jobs:
  deploy-em-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Realizando Deploy em Staging
        run: |
          echo "Realizando deploy em staging..."
          sleep 5
          echo "Deploy em staging concluído com sucesso."

  aprovar-merge-to-production:
    needs: deploy-em-staging
    runs-on: ubuntu-latest
    environment:
      name: production
      # A aprovação manual será exigida aqui
    steps:
      - name: Aguardar aprovação manual
        run: echo "Esperando aprovação para publicação em produção..."

      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Criar Pull Request staging → main
        id: criar_pr
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh repo set-default ${{ github.repository }}
          PR_URL=$(gh pr create --base main --head staging --title "Publicar em produção" --body "Merge automático após aprovação" || true)
          echo "PR_URL=$PR_URL" >> $GITHUB_ENV
          PR_NUMBER=$(echo "$PR_URL" | grep -o '[0-9]*$')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      - name: Merge Pull Request
        if: env.PR_NUMBER != ''
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh pr merge $PR_NUMBER --merge --repo ${{ github.repository }}
