name: 🔧 Staging Workflow

on:
  workflow_dispatch:

jobs:
  build-staging:
    name: 🔨 Build & Test Staging
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout do repositório
        uses: actions/checkout@v4

      - name: 🔧 Rodando testes de staging
        run: |
          echo -e "\033[1;34m🚀 Iniciando build e testes no ambiente de staging...\033[0m"
          sleep 2
          echo -e "\033[1;32m✅ Testes de staging concluídos com sucesso!\033[0m"
