# .github/workflows/teste-workflow.yml
name: TesteWorkflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Executando testes
        run: |
          echo "Simulando testes de homologação..."
          sleep 10
          echo "Testes concluídos com sucesso."
